### ISSUE TITLE
Terms of Service Section 5.1 prohibits building databases

### ISSUE THREAD

**Issue by ryan-lp** [Podcastindex-org/legal#1]
Originally discussed in https://github.com/Podcastindex-org/podcast-namespace/discussions/558

The relevant section:

> 5. **Prohibitions on Content** - Unless expressly permitted by the content owner or by applicable law,
>    you will not, and will not permit your end users or others acting on your behalf to, do the following
>    with content returned from the APIs:
>
>    1. Scrape, build databases, or otherwise create permanent copies of such content, or keep cached
>       copies longer than permitted by the cache header;
>    2. Copy, translate, modify, create a derivative work of, sell, lease, lend, convey, distribute,
>       publicly display, or sublicense to any third-party;

I understand from https://github.com/Podcastindex-org/podcast-namespace/discussions/558 that the intention was to prevent database scraping, but the wording above is strong enough to prohibit many other kinds of interactions including one that was intended:

> tracks the /recent/data endpoint and just follows along with all the feed updates.

Users of the API can of course track the /recent/data endpoint but cannot build databases from the content returned from that endpoint. I asked in the previous discussion about what concrete limit the cache headers impose on this, but that question was not addressed.

5.2 was also quoted above in that it may also relate to the unintended limitations of 5.1.

> There are a bunch of ways to stay up to date actually. I’m glad to share them.

Aside from the issue with the terms of service, I would be interested in ways to stay up to date that do not involve hitting a centralised API, but I don't know which repository would be most appropriate to ask such a question. DB changes could be broadcast via podping but the itunes ID is what I really need and that is not transmitted via podping. Another option is to periodically publish database diffs at a predictable URL which include the itunes ID column. This could be distributed in a more decentralised way by following the common distribution model for linux (i.e. mirrors).

**Comment by daveajones** [comment]
Isn’t the weekly database download what you need?  There’s a link to it on our home page.  Or are you wanting all the episode metadata as well?

**Comment by ryan-lp** [comment]
I've moved that side question over to https://github.com/Podcastindex-org/database/issues/33 since this issue is about Section 5 of the Terms of Service.

**Comment by daveajones** [comment]
Plan to visit the legal terms in the board room on Friday.  So much of our terms are just boilerplate stuff that haven't been looked at since the beginning.  Probably need to go over it with a fine tooth comb and see what needs to be changed/clarified.

**Comment by daveajones** [comment]
To be clear, we don't care if you build a database.  We literally give you one to start with.  Just have to have a legal person figure out how to word that.

**Comment by ryan-lp** [comment]
> Plan to visit the legal terms in the board room on Friday.

Please share the minutes afterwards.

**Comment by daveajones** [comment]
> > Plan to visit the legal terms in the board room on Friday.
> 
> Please share the minutes afterwards.

The "board room" is just our podcast.  You can listen along.  :-)

**Comment by ryan-lp** [comment]
> The "board room" is just our podcast. You can listen along. :-)

I really would if there were a "Skip politics/mudslinging/disparagement/derision" button. I appreciate all that you and Adam do to advance podcasting, but if it's all the same, I would prefer to just participate on GitHub where things tend to be more squarely focused on the primary goal: advancing podcasting.

If minutes were ever to be taken at the boardroom, I'm sure they would reflect only the best of what you do and not the worst.

**Comment by ryan-lp** [comment]
I listened to the latest "boardroom" on your suggestion in order to keep abreast of the latest decisions that are being made, in particular regarding the terms of service. Would you like to hear my thoughts on the experience, or do you sort of know what I'm going to say? (I don't want to say it you already have a sense of what I might say.)

**Comment by daveajones** [comment]
I’m sorry you don’t like the podcast. No reason to listen if it isn’t enjoyable. I’ll just update this thread later when we get to talk about the terms. Ran out of time this week. My apologies.

**Comment by brianoflondon** [comment]
I'm not a lawyer, but as you know I'm legally adjacent, I suspect that this is absolutely sufficient:

>Prohibitions on Content - **Unless expressly permitted by the content owner** or by applicable law, you will not, and will not permit your end users or others acting on your behalf to, do the following with content returned from the APIs:

I'm certainly creating a new database, from the downloaded database for the GUID resolver, and I would consider that the fact my starting point is a database I've downloaded with express permission extends to my further creation of a new database of GUIDs.

The rest of a scan of the T&Cs seem fine, this could be cleared up with another sentence but honestly I can't see who is ever going to sue or be sued under these terms.

**Comment by ryan-lp** [comment]
Out of curiosity, who do you think is the content owner of the content returned by the API? Do you interpret it to be owned by the podcast author who wrote that text, or are you thinking more along the lines of the copyright owner of the compilation - i.e. the whole database?

And can you point to this "express permission" that would permit app developers to build databases from content returned by the API?

If your answer to the first question is that the Podcast Index is the content owner and also that they have actually expressly permitted scraping the API, building databases from the API, or otherwise create permanent copies of content from the API, or keep cached copies longer than permitted by the cache header from the API, then it would be better to move that express permission into this legal document. In which case it would be very weird to say in the terms that "you can't do this unless we say you can, and by the way, we say you can". That wording cancels itself and can be simplified with clearer language. (edit: well not "very" weird, unless such express permission exactly cancels out one or more of the items in the list, in which case they shouldn't be in the list in the first place).

But if your answer to the first question is that the podcast authors themselves are the content owners, then in most cases this is not "expressly permitted". It may be assumed by many to be "implicitly" permitted, but even then, there is legal debate about that. However, I would find this whole interpretation very weird because the intent of this bit was, according to @daveajones , to prevent people from scraping the whole compilation.

While I might prefer the first interpretation, I think the wording is sufficiently ambiguous that it could do with a definition of terms, because different parts of the document seem to sometimes hint at it referring to the compilation, and other times referring to the individual content.

> honestly I can't see who is ever going to sue or be sued under these terms.

I'm sure that's what Google assumed about Sun Microsystems before it was taken over by different people, the far more litigious Oracle (who then sued Google in spite of the wink/handshake Sun had previously given them that they could use Java in Android). I think it's a mistake not to trust the legal document over the people because the people can change but the legal agreement is binding.

(Apologies this turned out longer than intended. In the end, I have raised an issue that probably affects you more than it affects me since you are the one who is using the API and is bound by its terms, while I am not using the API, instead replicating the database directly under the terms of the MIT license, outside of the API. So if nobody else who uses the API actually has this concern, I should probably not be one to make a noise about it.)

**Comment by ryan-lp** [comment]
> I’m sorry you don’t like the podcast. No reason to listen if it isn’t enjoyable. I’ll just update this thread later when we get to talk about the terms. Ran out of time this week. My apologies.

Is there any chance that you will publish the weekly minutes?

**Comment by daveajones** [comment]
We talked about the terms last week and are going to get a lawyer to look over everything and pull out the stuff that is confusing. Until then I’m going to remove this part about building a database.

**Comment by ryan-lp** [comment]
Let me try this again. Please:

Publish weekly minutes or replicate boardroom comments on relevant GitHub discussions for an inclusive space. Open source contributors need updates without political undertones. Don't isolate potential contributors by sharing crucial information only on a divisive show. Foster a welcoming environment or risk losing valuable contributors. Keep the focus on the project, not politics.

**Comment by daveajones** [comment]
I have a day job and a family Ryan.  It takes all I can do to just keep everything running.  I have 587 emails in my podcast index inbox and feel underwater all the time.  Please don't demand that I add even more work to my plate.  I'm sorry you find our show offensive, but your demands on my time do nothing but stress me out.  These types of comments are what make people leave FOSS projects.
